In [5]:
print("Prince")

Prince


In [6]:
name = "Prince"
print(name)

Prince


In [7]:
x = 5

x += 3      # x = x + 3
print(x)

x -= 3      # x = x - 3
print(x)

x *= 3      # x = x * 3
print(x)

x /= 3      # x = x / 3
print(x)

x %= 3      # x = x % 3
print(x)

x //= 3     # x = x // 3
print(x)

8
5
15
5.0
2.0
0.0


In [8]:
x=5
print(x<5 or x<10)

True


In [9]:
x=5
print(x>0 and x>10)

False


In [10]:
x=["apple","banana"]
y=["banana","apple"]
z=x
print(x is z)
print(x is y)
print(x == y)

True
False
False


In [11]:
thisset ={"apple","banana","grapes"}
print(thisset)

{'apple', 'grapes', 'banana'}


In [12]:
fruits ={"apple","banana","grapes"}
for fruit in fruits:
   print(fruit)

apple
grapes
banana


In [13]:
fruits ={"apple","banana","grapes"}
fruits.remove("banana")
print(fruits)

{'apple', 'grapes'}


In [14]:
thisdict={
    "brand":"ford",
    "year":2026
}
print(thisdict)

{'brand': 'ford', 'year': 2026}


In [15]:
student={
    "name":"vikky",
    "age":24
}
print(student)

{'name': 'vikky', 'age': 24}


In [ ]:
student = {
    "name": "vikky"
}

student.update({
    "city": "varanasi",
    "age": 24
})

print(student)

{'name': 'vikky', 'city': 'varanasi', 'age': 24}


In [1]:
i=1 
while i<6:
    print(i)
    if i==3:
      break
    i+=1

1
2
3


In [3]:
fruits = ["apple","banana","cherry"]
for x in fruits:
    print(x)
    if x=="banana":
        break

apple
banana


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.5.2


In [6]:
#1D Array
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [8]:
#2D Array
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
#3D Array
import numpy as np

arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [4, 2],
        [6, 4]
    ]
])

print(arr)

[[[1 2]
  [3 4]]

 [[4 2]
  [6 4]]]


In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [12]:
print(arr.shape)

(2, 3)


In [13]:
print(arr.size)

6


In [14]:
#Zeros
print(np.zeros((5,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [15]:
print(np.ones((2,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
#identity matrix
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
print(np.full((3,2),100))

[[100 100]
 [100 100]
 [100 100]]


In [20]:
print(np.random.randint(1,100,(4,4)))

[[42 56 80 11]
 [70 47 60 87]
 [ 5 88 92 78]
 [74 55 74 91]]


In [22]:
print(np.arange(1,20))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [23]:
print(np.arange(1,20,3))

[ 1  4  7 10 13 16 19]


In [5]:
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
#Flatten
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
#INDEXING
#1D
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


In [12]:
#2D 
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
print(arr[0,2])
print(arr[1,1])


3
5


In [15]:
#Slicing
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(arr[2:7])
print(arr[:7])
print(arr[1:])

[2 3 4 5 6]
[0 1 2 3 4 5 6]
[1 2 3 4 5 6 7 8 9]


In [4]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.sum(axis = 0))
print(arr.sum(axis = 1))

In [3]:
#Boolean Indexing
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [10]:
#Where
arr=np.array([10,20,30,40])
print(np.where(arr>20))

(array([2, 3]),)


In [11]:
#Sorting
arr=np.array([5,2,9,1])
print(np.sort(arr))

[1 2 5 9]


In [12]:
#Unique values
arr=np.array([1,2,2,3,3,4])
print(np.unique(arr))

[1 2 3 4]


In [14]:
#Concatenation
a=np.array([1,2])
b=np.array([3,4])
print(np.concatenate((a,b)))

[1 2 3 4]


In [15]:
#Vertical Concatenation 
A=np.array([1,2])
B=np.array([3,4])
print(np.vstack((A,B)))

[[1 2]
 [3 4]]


In [ ]:
#Horizontal Concatenation 
print(np.hstack((A,B)))

[1 2 3 4]


In [ ]:
#Split
import numpy as np

arr = np.arange(10)

print(np.split(arr, 5))

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [ ]:
#BraodCasting
arr=np.array([1,2,3])
print(arr+10)

[11 12 13]


In [ ]:
#2DBraodCasting
A=np.array([[1],[2],[3]])
B=np.array([10,20,30])
print(A+B)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [5]:
#Statistics
arr=np.array([1,2,3,4,5])
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))
print(np.percentile(arr,50))


3.0
3.0
2.0
1.4142135623730951
3.0


In [6]:
#Copy Vs View
arr = np.array([1, 3, 4])

view = arr.view()
copy = arr.copy()

arr[0] = 100

print(view)
print(copy)

[100   3   4]
[1 3 4]


In [7]:
#Masking
arr = np.arange(20)

mask = arr % 2 == 0

print(arr[mask])

[ 0  2  4  6  8 10 12 14 16 18]


In [9]:
#File Handling
arr = np.arange(10)

np.save("data.npy", arr)

In [10]:
#load
data = np.load("data.npy")

In [11]:
print(data)


[0 1 2 3 4 5 6 7 8 9]


In [12]:
#Universal Functions(ufunc)
arr=np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.square(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))


[1. 2. 3. 4.]
[  1  16  81 256]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


In [13]:
#Advanced Indexing
arr=np.arange(20)
print(arr)
print(arr[[2,4,6]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2 4 6]


In [14]:
#Fancy Indexing
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(arr[[0, 2]])

[[1 2]
 [5 6]]


In [15]:
#Braodcasting Example
a = np.ones((3, 3))
print(a)

b = np.array([1, 2, 3])
print(a + b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
